#! /bin/bash

# Written by Ian Nesbitt, 2017. Distributed under AGPL3.0 License.
# Converts set of images to timelapse and copies to web location
# Requires ffmpeg

# frames per second
FPS=10

# the file
FILE=$(date '+%Y-%m-%d')-${PWD##*/}.mp4
# the image repository
LOC=$(pwd) # get current folder (default)
# the repository
TMP=$LOC/tmp
DEST=$LOC/0video
mkdir $TMP
mkdir $DEST

if [ -d "$LOC" ]; then
  cd "$LOC"

  # writes list of files, numbers each list item,
  # stores number and filename as vars, then renames files with numbering.
  # numbering is in %d format starting at 1.jpg
  ls | cat -n | while read n f; do cp "$f" "$TMP/$n.jpg"; done
  cd $TMP
  # converts filenames with %d format to 30fps mp4 starting at 1.jpg
  ffmpeg -y -start_number 1 -r $FPS  -i \%d.jpg -c:v libx264 "$DEST/$FILE"

  # using the assumed noon image as the cover image
  # not a huge deal if not there; video will default to first frame

  # removes jpgs in tmp folder
  rm *.jpg

  # removes temp folder
  #cd ../; rm -r $TMP

fi

